config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import user.urls

urlpatterns = [
    path('', include(main.urls, namespace='main')),
    path('admin/', admin.site.urls),
    path('users/', include(user.urls, namespace='user')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<int:product_id>/plans', views.PlanListView.as_view(), name='plans'),
    path('add-to-basket/', views.add_to_basket, name='add_to_basket'),
    path('delete-from-basket/<int:basket_item_id>/', views.delete_basket_item, name='delete_from_basket'),
    path('subscriptions/new/', views.SubscriptionNewView.as_view(), name='subscription_new'),
    path('subscription/create/<int:plan_id>/', views.create_subscription, name='create_subscription'),
    path('subscriptions/', views.SubscriptionListView.as_view(), name='subscriptions'),
    path('subscriptions/<int:pk>/', views.SubscriptionUpdateView.as_view(), name='subscription_update'),
]

user/urls.py
from typing import List

from django.contrib.auth.views import LoginView
from django.urls import include, path
from django.urls.resolvers import URLPattern

from user import forms
from user import views

app_name = 'user'

urlpatterns: List[URLPattern] = [
    path('sign_up/', views.CustomRegistrationView.as_view(), name='sign_up'),
    path('login/', LoginView.as_view(form_class=forms.AuthenticationForm), name='login'),
    path('', include('django_registration.backends.one_step.urls')),
    path('', include('django.contrib.auth.urls')),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account/edit/', views.AccountUpdateView.as_view(), name='account_edit'),
    path('account/address/edit/', views.AddressUpdateView.as_view(), name='address_edit'),
]

user/models.py
import logging
from typing import List

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email=email, password=password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Super user must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Super user must have is_superuser=True')
        return self._create_user(email=email, password=password, **extra_fields)

    def get_or_none(self, *args, **kwargs):
        try:
            return self.model.objects.get(*args, **kwargs)
        except self.model.DoesNotExist:
            return None


class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True, null=False, blank=False, db_index=True,
                              error_messages={'unique': _('A user with this email already exists.')})
    date_updated = models.DateTimeField(_('date updated'), auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS: List[str] = []
    objects = UserManager()

    def _show(self):
        return {key: value for key, value in self.__dict__.items() if not key.startswith('_')}


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='addresses', db_index=True)
    address1 = models.CharField('Address', max_length=120, null=False, blank=False)
    address2 = models.CharField('Address', max_length=120, null=True, blank=True)
    city = models.CharField('City', max_length=60, null=False, blank=False)
    postcode = models.CharField('Postcode', max_length=10, null=False, blank=False)
    country = models.CharField('Country', max_length=60, null=False, blank=False)
    phone = models.CharField('Phone number', max_length=30, null=True, blank=True)
    is_billing = models.BooleanField(default=True, null=False, blank=False)
    billing_address1 = models.CharField('Billing address', max_length=120, null=True, blank=True)
    billing_address2 = models.CharField('Billing address', max_length=120, null=True, blank=True)
    billing_city = models.CharField('Billing city', max_length=60, null=True, blank=True)
    billing_postcode = models.CharField('Billing postcode', max_length=10, null=True, blank=True)
    billing_country = models.CharField('Billing country', max_length=60, null=True, blank=True)
    date_updated = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True, null=False)

    def _show(self):
        return {key: value for key, value in self.__dict__.items() if not key.startswith('_')}

user/forms.py
import logging

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UsernameField, UserCreationForm as DjangoRegistrationForm
from django_registration import validators

from user import models
from user.tasks import send_welcome_email_to_user

logger = logging.getLogger(__name__)


class RegistrationForm(DjangoRegistrationForm):
    first_name = forms.CharField(label='First name', required=True, max_length=60)
    last_name = forms.CharField(label='Last name', required=True, max_length=60)

    class Meta(DjangoRegistrationForm.Meta):
        model = models.User
        fields = ('email', 'first_name', 'last_name')
        field_classes = {'email': UsernameField}

    error_css_class = 'error'
    required_css_class = 'required'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].validators.extend(
            (validators.HTML5EmailValidator(), validators.validate_confusables_email,
             validators.CaseInsensitiveUnique(models.User, 'email', validators.DUPLICATE_EMAIL))
        )
        self.fields['email'].required = True

    def send_welcome_email(self):
        email = self.cleaned_data.get('email')
        send_task = send_welcome_email_to_user.delay(email)
        logger.info(f'Send a welcome task to {email}, task: {send_task.id}')


class AuthenticationForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user = authenticate(request=self.request, email=email, password=password)
            if self.user is None:
                raise forms.ValidationError('Invalid email or password.')
            logger.info(f'Authenticate successfully {email}')
            return self.cleaned_data

    def get_user(self):
        return self.user


class AddressForm(forms.ModelForm):
    class Meta:
        model = models.Address
        fields = ['user', 'address1', 'address2', 'city', 'postcode', 'country', 'phone', 'billing_address1',
                  'billing_address2', 'billing_city', 'billing_country', 'billing_postcode']

user/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView
from django_registration import signals
from django_registration.backends.one_step.views import RegistrationView

from user.forms import RegistrationForm, AddressForm
from user.models import User, Address


class CustomRegistrationView(RegistrationView):
    form_class = RegistrationForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        if 'address_form' not in kwargs:
            kwargs['address_form'] = AddressForm()
        return super().get_context_data(**kwargs)

    def register(self, form):
        new_user, form = form
        new_user = authenticate(
            **{
                User.USERNAME_FIELD: new_user.get_username(),
                "password": form.cleaned_data["password1"],
            }
        )
        login(self.request, new_user)
        signals.user_registered.send(sender=self.__class__, user=new_user, request=self.request)
        return new_user

    def form_valid(self, form: RegistrationForm):
        address_params: dict = {k: self.request.POST.get(k) for k in AddressForm.base_fields if k != 'user'}
        with transaction.atomic():
            sid = transaction.savepoint()
            new_user: User = form.save()
            address_params['user'] = new_user.id
            address_form: AddressForm = AddressForm(address_params)
            if address_form.is_valid():
                new_user = self.register((new_user, form))
                address_form.save()
            else:
                transaction.savepoint_rollback(sid)
        if address_form.is_valid():
            return HttpResponseRedirect(self.get_success_url(new_user))
        else:
            return self.render_to_response(self.get_context_data(form=form, address_form=address_form))


class AccountView(LoginRequiredMixin, TemplateView):
    template_name = 'account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['address'] = self.request.user.addresses.first()
        return context


class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'account_edit.html'
    fields = ['first_name', 'last_name']
    success_url = reverse_lazy('user:account')

    def get_object(self, queryset=None):
        return self.request.user


class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = Address
    template_name = 'address_edit.html'
    fields = ['address1', 'address2', 'city', 'postcode', 'country', 'phone', 'billing_address1', 'billing_address2',
              'billing_city', 'billing_country', 'billing_postcode']
    success_url = reverse_lazy('user:account')

    def get_object(self, queryset=None):
        return self.request.user.addresses.first()

user/templates/account.html
{% extends 'base.html' %}

{% block title %}My account - {{ block.super }}{% endblock %}
{% block content %}
    <h1>My account</h1>

    <h3>Account details</h3>
    <ul>
        <li>Email: {{ user.email }}</li>
        <li>First name: {{ user.first_name }}</li>
        <li>Last name: {{ user.last_name }}</li>
        <li>Created at: {{ user.date_created }}</li>
        <li>Updated at: {{ user.date_updated }}</li>
        {% if user.is_superuser %}
            <li>Is superuser: True</li>
        {% endif %}
    </ul>
    <h3>Address details</h3>
    <ul>
        <li>Address: {{ address.address1 }}</li>
        {% if address.address2 %}
            <li>Address 2: {{ address.address2 }}</li>
        {% endif %}
        <li>Postcode: {{ address.postcode }}</li>
        <li>City: {{ address.city }}</li>
        <li>Country: {{ address.country }}</li>
        <li>Phone: {{ address.phone }}</li>
        {% if not address.is_billing %}
            <li>Billing address: {{ address.billing_address1 }}</li>
            <li>Billing postcode: {{ address.billing_ostcode }}</li>
            <li>Billing city: {{ address.billing_city }}</li>
            <li>Billing country: {{ address.billing_country }}</li>
        {% endif %}
    </ul>
    <div class="ui divider"></div>
    <a href="{% url 'user:account_edit' %}" class="ui button primary">Edit account details</a>
    <a href="{% url 'user:address_edit' %}" class="ui button orange">Edit address details</a>
{% endblock %}

user/templates/account_edit.html
{% extends 'base.html' %}

{% block title %}Account edit - {{ block.super }}{% endblock %}
{% block content %}
    <h1>Edit my account details</h1>
    <div class="ui divider"></div>
    <form method="post" class="ui form edit-account">
        {% csrf_token %}
        <div class="account-info">
            <div class="field {% if form.first_name.errors %}error{% endif %}">
                {{ form.first_name.label_tag }}
                <input type="text" id="id_first_name" name="first_name" value="{{ form.first_name.value|default:'' }}">
            </div>
            <div class="field {% if form.last_name.errors %}error{% endif %}">
                {{ form.last_name.label_tag }}
                <input type="text" id="id_last_name" name="last_name" value="{{ form.last_name.value|default:'' }}">
            </div>
        </div>
        <div class="ui hidden divider"></div>
        <button class="ui button green" type="submit">Save</button>
        <a href="{% url 'user:account' %}" class="ui button negative">Cancel</a>
    </form>
{% endblock %}

user/templates/address_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Address edit - {{ block.super }}{% endblock %}
{% block content %}
    <h1>Edit my address details</h1>
    <div class="ui divider"></div>
    <form method="post" class="ui form edit-account">
        {% csrf_token %}
        {% include 'django_registration/_address_form.html' with address_form=form %}
        <div class="ui hidden divider"></div>
        <button class="ui button green" type="submit">Save</button>
        <a href="{% url 'user:account' %}" class="ui button negative">Cancel</a>
    </form>
{% endblock %}
{% block js %}
    <script src="{% static "js/addresses.js" %}"></script>
{% endblock %}