config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import user.urls

urlpatterns = [
    path('', include(main.urls, namespace='main')),
    path('admin/', admin.site.urls),
    path('users/', include(user.urls, namespace='user')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<int:product_id>/plans', views.PlanListView.as_view(), name='plans'),
    path('add-to-basket/', views.add_to_basket, name='add_to_basket'),
    path('delete-from-basket/<int:basket_item_id>/', views.delete_basket_item, name='delete_from_basket'),
    path('subscriptions/new/', views.SubscriptionNewView.as_view(), name='subscription_new'),
    path('subscription/create/<int:plan_id>/', views.create_subscription, name='create_subscription'),
    path('subscriptions/', views.SubscriptionListView.as_view(), name='subscriptions'),
    path('subscriptions/<int:pk>/', views.SubscriptionUpdateView.as_view(), name='subscription_update'),
]

user/urls.py
from typing import List

from django.contrib.auth.views import LoginView
from django.urls import include, path
from django.urls.resolvers import URLPattern

from user import forms
from user import views

app_name = 'user'

urlpatterns: List[URLPattern] = [
    path('sign_up/', views.CustomRegistrationView.as_view(), name='sign_up'),
    path('login/', LoginView.as_view(form_class=forms.AuthenticationForm), name='login'),
    path('', include('django_registration.backends.one_step.urls')),
    path('', include('django.contrib.auth.urls')),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account/edit/', views.AccountUpdateView.as_view(), name='account_edit'),
    path('account/address/edit/', views.AddressUpdateView.as_view(), name='address_edit'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "css/semantic.min.css" %}">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>{% block title %}SubsMan management system{% endblock %}</title>
</head>
<body>
{% if user.is_authenticated %}
    {% include 'navigation.html' %}
{% else %}
    <div class="ui visible inverted left vertical sidebar default">
        <div>
            <a href="/"><img src="{% static "logo.png" %}" class="nhm-logo" alt="logo"
                             style="height: 100px; width: 100px"/></a>
        </div>
        <div class="welcome">Welcome to SubsMan!</div>
        <div class="infotext">Please login or create new account to continue with product checkout.</div>
    </div>
{% endif %}
<div class="pusher">
    <div class="ui container">
        {% if user.is_authenticated %}{% include 'header.html' %}{% endif %}
        <div class="ui grid padded" style="padding: 0 10px;">
            <div class="sixteen wide column">
                <div class="basket-container">
                    {% if request.basket.count %}
                        {% include '_basket.html' with basket=request.basket %}
                    {% endif %}
                </div>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/semantic.min.js" %}"></script>
<script src="{% static "js/index.js" %}" type="module"></script>
<script src="https://www.gstatic.com/charts/loader.js"></script>
{% block js %}
{% endblock %}
</body>
</html>

templates/header.html
{% load static %}
<div class="ui grid padded" style="padding: 10px 10px 0 10px;">
    <div class="ten wide computer ten wide tablet sixteen wide mobile column">
        <div class="logo">
            <button id="sidebar-toggle" class="ui icon button basic compact">
                <i class="bars icon"></i>
            </button>
            <a href="/"><img src="{% static "logo_with_text.png" %}" class="nhm-logo" alt="logo"
                             style="height: 100%; max-height: 50px; max-width: 50px; width: 100%"/></a>
        </div>
    </div>
    <div class="six wide computer six wide tablet sixteen wide mobile column right aligned" id="notifications">
        <div class="notification-button ui icon top right pointing dropdown button basket-open">
            <i class="shopping basket icon"></i>
            <span class="button__badge">{% if request.basket %}{{ request.basket.count }}{% else %}0{% endif %} </span>
        </div>
        <div class="ui dropdown icon top right pointing">
            <div class="user-avatar-header">
                {{ user.first_name.0|upper }}{{ user.last_name.0|upper }}
            </div>
            <div class="menu">
                <a class="logout-link" rel="nofollow" data-method="delete" href="{% url 'user:logout' %}">
                    <div class="item">Logout</div>
                </a>
            </div>
        </div>
        <div class="user-full-name-header" title="{{ user.first_name }} {{ user.last_name }} ({{ user.email }})">
            {{ user.first_name }} {{ user.last_name }}
        </div>
    </div>
    <div class="sixteen wide column headline">
        <div class="ui divider" style="margin: 0;"></div>
    </div>
</div>

templates/navigation.html
<div class="ui inverted left vertical sidebar menu push visible" style="">
    <a class="item {% if request.resolver_match.url_name == '' %}active{% endif %}" href="/">Dashboard</a><br>
    <a class="item {% if request.resolver_match.url_name == 'account' %}active{% endif %}"
       href="{% url 'user:account' %}">My account</a>
    <a class="item {% if request.resolver_match.url_name == 'subscriptions' %}active{% endif %}"
       href="{% url 'main:subscriptions' %}">My subscriptions</a>
    <a class="item {% if request.resolver_match.url_name == 'users' %}active{% endif %}" href="#">Products</a>
    <a class="item {% if request.resolver_match.url_name == 'payment_sources' %}active{% endif %}" href="#">
        Plans
    </a>
</div>