config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

import main.urls
import user.urls

urlpatterns = [
    path('', include(main.urls, namespace='main')),
    path('admin/', admin.site.urls),
    path('users/', include(user.urls, namespace='user')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<int:product_id>/plans', views.PlanListView.as_view(), name='plans'),
    path('add-to-basket/', views.add_to_basket, name='add_to_basket'),
    path('delete-from-basket/<int:basket_item_id>/', views.delete_basket_item, name='delete_from_basket'),
    path('subscriptions/new/', views.SubscriptionNewView.as_view(), name='subscription_new'),
    path('subscription/create/<int:plan_id>/', views.create_subscription, name='create_subscription'),
    path('subscriptions/', views.SubscriptionListView.as_view(), name='subscriptions'),
    path('subscriptions/<int:pk>/', views.SubscriptionUpdateView.as_view(), name='subscription_update'),
]

main/models.py
from django.core.validators import MinValueValidator
from django.db import models

from user.models import User


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class ProductManager(ActiveManager):
    pass


class Product(models.Model):
    name = models.CharField('Name', null=False, blank=False, max_length=60)
    description = models.CharField('Description', null=True, blank=True, max_length=255)
    site = models.CharField('Site', null=False, blank=False, max_length=60)
    active = models.BooleanField('Active', null=False, default=True)
    product_code = models.CharField('Product code', null=True, blank=True, max_length=60)
    date_updated = models.DateTimeField(auto_now=True)
    date_created = models.DateTimeField(auto_now_add=True, null=False)

    objects = ProductManager()

    def __str__(self):
        return f'<Product: {self.name}>'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product-images')
    thumbnail = models.ImageField(upload_to='product-thumbnails', null=True, blank=True)


class PlanManager(ActiveManager):
    pass


class Plan(models.Model):
    PERIOD_UNITS = (('days', 'Day'), ('weeks', 'Week'), ('months', 'Month'), ('years', 'Year'))
    CURRENCIES = (('us', 'USD'), ('eur', 'EUR'), ('pln', 'PLN'))
    name = models.CharField('Plan name', null=False, blank=False, max_length=120)
    description = models.CharField('Description', null=True, blank=True, max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='plans', db_index=True)
    price = models.DecimalField('Price', null=False, blank=False, decimal_places=2, max_digits=8)
    period = models.IntegerField('Period', null=True, blank=True)
    period_unit = models.CharField('Period unit', choices=PERIOD_UNITS, max_length=20)
    active = models.BooleanField('Active', null=False, default=True, blank=True)
    currency_code = models.CharField('Currency', choices=CURRENCIES, max_length=10)
    recurring = models.BooleanField('Recurring', null=False, blank=True, default=False)
    date_updated = models.DateTimeField(auto_now=True, editable=False)
    date_created = models.DateTimeField(auto_now_add=True, null=False)

    objects = PlanManager()

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'<Plan: {self.name}>'


class PlanItem(models.Model):
    name = models.CharField('Item name', null=False, blank=False, max_length=120)
    description = models.CharField('Description', null=True, blank=True, max_length=255)
    value = models.CharField('Value', null=False, blank=False, max_length=255)
    value_unit = models.CharField('Value unit', null=False, blank=False, max_length=120)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, db_index=True, related_name='items')
    date_updated = models.DateTimeField(auto_now=True, editable=False)
    date_created = models.DateTimeField(auto_now_add=True, null=False)

    def __str__(self):
        return f'<PlanItem: {self.name}>'


class SubscriptionManager(ActiveManager):
    pass


class Subscription(models.Model):
    status = models.CharField('Status', null=True, blank=True, max_length=30)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='subscriptions', db_index=True)
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT, related_name='subscriptions', db_index=True)
    recurring = models.BooleanField('Recurring', null=False, blank=True, default=False)
    term_start = models.DateTimeField('Term start', null=True, blank=True)
    term_end = models.DateTimeField('Term end', null=True, blank=True)
    active = models.BooleanField('Active', null=False, default=True, blank=True)
    date_updated = models.DateTimeField(auto_now=True, editable=False)
    date_created = models.DateTimeField(auto_now_add=True, null=False)

    objects = SubscriptionManager()

    def __str__(self):
        return f'<Subscription of plan:{self.plan.name}>'


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, 'Open'), (SUBMITTED, 'Submitted'))

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=OPEN, null=True, blank=True)
    date_updated = models.DateTimeField(auto_now=True, editable=False)
    date_created = models.DateTimeField(auto_now_add=True, null=False)

    @property
    def count(self):
        return sum(i.quantity for i in self.basketitem_set.all())


class BasketItem(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    date_updated = models.DateTimeField(auto_now=True, editable=False, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=False)

main/forms.py
from django import forms

from main.models import Subscription


class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['plan', 'user', 'recurring', 'term_start', 'term_end', 'status']

main/views.py
import datetime as ddt

from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView

from main.forms import SubscriptionForm
from main.models import Product, Plan, Basket, BasketItem, Subscription


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.active().all()
        context['subscriptions'] = self.request.user.subscriptions.all()[:5]
        return context


class PlanListView(LoginRequiredMixin, ListView):
    model = Plan
    paginate_by = 3
    template_name = 'plan_list.html'

    def get_queryset(self):
        return Product.objects.active().get(pk=self.kwargs['product_id']).plans.active()


@login_required
def add_to_basket(request):
    plan_id = request.GET.get('plan_id')
    plan = get_object_or_404(Plan, pk=plan_id)
    basket = request.basket
    if not basket:
        basket = Basket.objects.create(user=request.user)
        request.session['basket_id'] = basket.id
    basket_item, created = BasketItem.objects.get_or_create(basket=basket, plan=plan)
    if not created:
        basket_item.quantity += 1
        basket_item.save()
    return HttpResponseRedirect(reverse('main:home'))


@login_required
def delete_basket_item(request, basket_item_id):
    basket = request.basket
    if not basket:
        raise Http404('No basket provided')
    basket_item = get_object_or_404(BasketItem, pk=basket_item_id)
    basket_item.delete()
    return HttpResponseRedirect(reverse('main:home'))


class SubscriptionNewView(LoginRequiredMixin, TemplateView):
    template_name = 'subscription_new.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        plan_id = self.request.GET.get('plan_id')
        plan = get_object_or_404(Plan, pk=plan_id)
        ctx['plan'] = plan
        return ctx


@login_required
def create_subscription(request, plan_id):
    plan = get_object_or_404(Plan, pk=plan_id)
    plan_terms = {plan.period_unit: plan.period}
    this_time = ddt.datetime.now()
    # noinspection PyTypeChecker
    term_end = this_time + relativedelta(**plan_terms)
    subscription_data = dict(plan=plan, user=request.user, term_start=this_time,
                             term_end=term_end, status='New')
    subscription_form = SubscriptionForm(subscription_data)
    if subscription_form.is_valid():
        subscription_form.save()
        return HttpResponseRedirect(reverse('main:home'))


class SubscriptionListView(LoginRequiredMixin, ListView):
    template_name = 'subscriptions.html'
    model = Subscription

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class SubscriptionUpdateView(LoginRequiredMixin, UpdateView):
    model = Subscription
    template_name = 'subscription_update.html'
    fields = ['recurring', 'plan']
    success_url = reverse_lazy('main:subscriptions')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['plans'] = self.object.plan.product.plans.all()
        return ctx

main/templates/_basket.html
<div class="ui segment">
    <div class="ui three column grid basket">
        <div style="position: absolute; right: 20px; top: 10px; font-size: 18px; cursor: pointer; z-index: 2"
             class="basket-close">x
        </div>
        {% for item in basket.basketitem_set.all %}
            {% include '_plan_card.html' with plan=item.plan basket_item=item %}
        {% endfor %}
    </div>
</div>

main/templates/_plan_card.html
<div class="column">
    <div class="ui fluid card">
        <div class="content">
            <div class="header" style="text-align: center;">{{ plan.name }}</div>
            <div class="description" style="text-align: center;">
                <strong style="color: black">{{ plan.price }} {{ plan.currency_code | upper }}</strong>
                <br/>
                {{ plan.description }}
            </div>
            <div class="ui divider"></div>
            <div class="ui two column right aligned grid">
                {% for item in plan.items.all %}
                    <div class="right aligned column"
                         title="{{ item.description }}">{{ item.name }}</div>
                    <div class="left aligned column">
                        <strong>{{ item.value }}-{{ item.value_unit }}</strong>
                    </div>
                {% endfor %}
            </div>
            <div class="ui divider"></div>
        </div>
        {% if request.resolver_match.url_name == 'plans' %}
            <a href="{% url 'main:add_to_basket' %}?plan_id={{ plan.id }}">
                <div class="ui bottom attached button">
                    <i class="add icon"></i>
                    Add to basket
                </div>
            </a>
            <a href="{% url 'main:subscription_new' %}?plan_id={{ plan.id }}">
                <div class="ui bottom attached button" style="background-color: #00b27b; color: white">
                    PURCHASE
                </div>
            </a>
        {% endif %}
        {% if request.resolver_match.url_name == 'home' %}
            <div class="ui bottom attached button" style="background-color: #F2F8FD">
                <a href="{% url 'main:subscription_new' %}?plan_id={{ plan.id }}" class="ui button green">PURCHASE</a>
                <a href="{% url 'main:delete_from_basket' basket_item.id %}" class="ui button red">DELETE</a>
            </div>
        {% endif %}
    </div>
</div>

main/templates/_subscriptions_list.html
<div class="ui segment">
    <h4>YOUR SUBSCRIPTIONS</h4>
    <div class="ui hidden divider"></div>
    <table class="ui small very basic table">
        <thead>
        <tr>
            <th></th>
            <th>Product</th>
            <th>Plan</th>
            <th>Purchase date</th>
            <th>Expiration date</th>
            <th>Renewing</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for subscription in subscriptions %}
            <tr>
                <td>
                    <img src="{{ subscription.plan.product.images.first.image.url }}" alt="{{ product.name }}"
                         style="height: 28px;">
                </td>
                <td><strong>{{ subscription.plan.product.name }}</strong></td>
                <td><strong>{{ subscription.plan.name }}</strong></td>
                <td>{{ subscription.term_start|date:"SHORT_DATE_FORMAT" }}</td>
                <td>{{ subscription.term_end|date:"SHORT_DATE_FORMAT" }}</td>
                <td>{{ subscription.recurring|yesno }}</td>
                <td><a href="{% url 'main:subscription_update' subscription.id %}" class="ui button tiny orange">Manage</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

main/templates/home.html
{% extends 'base.html' %}
{% block title %}Dashboard - {{ block.super }}{% endblock %}
{% block content %}
    {% if subscriptions %}
        {% include '_subscriptions_list.html' with subscriptions=subscriptions %}
    {% endif %}
    <div class="ui segment" style="background: #e7eef5;">
        <h4>PRODUCTS</h4>
        <div class="ui hidden divider"></div>
        <table class="ui small very basic table">
            <tbody>
            {% for product in products %}
                <tr>
                    <td>
                        <img src="{{ product.images.first.image.url }}" alt="{{ product.name }}"
                             style="height: 28px;">
                    </td>
                    <td><strong>{{ product.name }}</strong></td>
                    <td class="status">{{ product.description }}.</td>
                    <td>
                        <a href="{{ product.site }}" target="_blank" class="ui button tiny blue">FIND OUT MORE</a>
                        <a href="{% url 'main:plans' product.id %}" class="ui button tiny green">PLANS</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

main/templates/plan_list.html
{% extends 'base.html' %}
{% block title %}Plans - {{ block.super }}{% endblock %}
{% block content %}
    <div class="ui segment">
        <div class="ui three column grid">
            {% for plan in plan_list %}
                {% include '_plan_card.html' with plan=plan %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

main/templates/subscription_new.html
{% extends 'base.html' %}
{% block title %}New subscription{% endblock %}
{% block content %}
    <div class="ui segment">
        <div class="ui grid">
            <div class="six wide column">
                <img src="{{ plan.product.images.first.image.url }}" alt="{{ plan.product.name }}"
                     style="height: 28px;">
                <h3>
                    <div><strong>{{ plan.name }}</strong></div>
                </h3>
                <h5>
                    <div>{{ plan.price }} {{ plan.currency_code | upper }}</div>
                </h5>
            </div>
            <div class="ten wide column">
                <div class="ui two column right aligned grid">
                    {% for item in plan.items.all %}
                        <div class="right aligned column" title="{{ item.description }}">
                            {{ item.name }}
                        </div>
                        <div class="left aligned column">
                            <strong>{{ item.value }}-{{ item.value_unit }}</strong>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="ui divider"></div>
        <a href="{% url 'main:create_subscription' plan.id %}" class="ui button positive">Create Subscription</a>
    </div>
{% endblock %}

main/templates/subscription_update.html
{% extends 'base.html' %}
{% block title %}Edit your subscription - {{ block.super }}{% endblock %}
{% block content %}
    <div class="ui segment">
        <h4>Edit your subscription</h4>
        <form method="post" class="ui form">
            {% if form.errors %}
                <div id="error_explanation">
                    <h2>Errors prohibited this user from being saved:</h2>
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ field.label }}: {{ error|escape }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% csrf_token %}
            <div class="field">
                <div class="ui selection dropdown">
                    <input type="hidden" name="plan" value="{{ form.plan.value|default:'' }}">
                    <i class="dropdown icon"></i>
                    <div class="default text">{{ object.plan.name }}</div>
                    <div class="menu">
                        {% for plan in plans %}
                            <div class="item" data-value="{{ plan.id }}">{{ plan.name }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="ui checkbox">
                    <input name="subscription_update_recurring" type="hidden" value="0">
                    <input class="recurring_subscription" type="checkbox" value="1"
                           {% if form.recurring.value %}checked{% endif %} name="recurring"
                           id="subscription_update_recurring">
                    <label for="subscription_update_recurring">Renewing subscription</label>
                </div>
            </div>
            <div class="ui divider"></div>
            <input class="ui button green" type="submit" name="commit" value="Submit"/>
        </form>
    </div>
{% endblock %}

main/templates/subscriptions.html
{% extends 'base.html' %}
{% block title %}Your subscriptions - {{ block.super }}{% endblock %}
{% block content %}
    {% if subscription_list %}
        {% include '_subscriptions_list.html' with subscriptions=subscription_list %}
    {% else %}
        <div class="ui segment">
            <h4>YOU DON'T HAVE SUBSCRIPTIONS YET</h4>
        </div>
    {% endif %}
{% endblock %}